# Generated by Django 4.2.4 on 2023-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardmanager', '0002_alter_board_macaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1),
            preserve_default=False,
        ),
    ]
