# Generated by Django 4.2.4 on 2023-11-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardmanager', '0003_board_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='defects',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
