# Generated by Django 4.2.4 on 2023-11-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardmanager', '0004_board_defects'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='where',
            field=models.CharField(choices=[('I', 'Internal'), ('E', 'External')], default='-', max_length=1),
            preserve_default=False,
        ),
    ]
