# Generated by Django 4.2.7 on 2023-11-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardmanager', '0005_board_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='actions',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
